# Generated by Django 5.1.5 on 2025-01-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmake',
            name='country',
            field=models.CharField(choices=[('JP', 'JP'), ('AU', 'AU'), ('CA', 'CA'), ('DE', 'DE'), ('US', 'US'), ('IN', 'IN'), ('FR', 'FR'), ('UK', 'UK')], default='US', max_length=50),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='type',
            field=models.CharField(choices=[('HATCHBACK', 'HATCHBACK'), ('SUV', 'SUV'), ('OTHER', 'OTHER'), ('WAGON', 'WAGON'), ('PICKUP', 'PICKUP'), ('Sedan', 'Sedan'), ('CONVERTIBLE', 'CONVERTIBLE'), ('SPORTS CAR', 'SPORTS CAR'), ('MINIVAN', 'MINIVAN'), ('COUPE', 'COUPE')], default='Sedan', max_length=50),
        ),
    ]
