# Generated by Django 5.1.5 on 2025-01-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_alter_carmake_country_alter_carmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmake',
            name='country',
            field=models.CharField(choices=[('IN', 'IN'), ('FR', 'FR'), ('DE', 'DE'), ('CA', 'CA'), ('JP', 'JP'), ('UK', 'UK'), ('US', 'US'), ('AU', 'AU')], default='US', max_length=50),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('MINIVAN', 'MINIVAN'), ('WAGON', 'WAGON'), ('COUPE', 'COUPE'), ('OTHER', 'OTHER'), ('PICKUP', 'PICKUP'), ('HATCHBACK', 'HATCHBACK'), ('CONVERTIBLE', 'CONVERTIBLE'), ('SPORTS CAR', 'SPORTS CAR'), ('Sedan', 'Sedan')], default='Sedan', max_length=50),
        ),
    ]
