# Generated by Django 5.1.5 on 2025-01-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_alter_carmake_country_alter_carmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmake',
            name='country',
            field=models.CharField(choices=[('IN', 'IN'), ('JP', 'JP'), ('US', 'US'), ('DE', 'DE'), ('FR', 'FR'), ('UK', 'UK'), ('CA', 'CA'), ('AU', 'AU')], default='US', max_length=50),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('CONVERTIBLE', 'CONVERTIBLE'), ('HATCHBACK', 'HATCHBACK'), ('OTHER', 'OTHER'), ('PICKUP', 'PICKUP'), ('SPORTS CAR', 'SPORTS CAR'), ('COUPE', 'COUPE'), ('SUV', 'SUV'), ('MINIVAN', 'MINIVAN'), ('WAGON', 'WAGON')], default='Sedan', max_length=50),
        ),
    ]
